### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by mario-zancanaro** [unboundfire/example-react-dashboard#2]
Hi!
After followed your installation guide I have:

test$ gulp
[17:44:15] Failed to load external module babel-register
[17:44:15] Requiring external module babel-core/register
[17:44:16] Using gulpfile ~/Documents/Apps/rdm/gulpfile.babel.js
[17:44:16] Starting 'build:watch'...
[17:44:16] Starting 'clean'...
[17:44:16] Finished 'clean' after 4.01 ms
[17:44:16] Starting 'build'...
[17:44:16] Starting 'assets'...
[17:44:16] Starting 'bundle'...
TypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (/User/test/Documents/Apps/rdm/node_modules/babel-eslint/index.js:199:40)
    at Object.exports.parse (/Users/test/Documents/Apps/rdm/node_modules/babel-eslint/index.js:410:5)
    at parse (/User/test/Documents/Apps/rdm/node_modules/eslint/lib/eslint.js:452:27)
    at EventEmitter.module.exports.api.verify (/Users/test/Documents/Apps/rdm/node_modules/eslint/lib/eslint.js:604:15)
    at processText (/User/test/Documents/Apps/rdm/node_modules/eslint/lib/cli-engine.js:231:23)
    at CLIEngine.executeOnText (/Users/test/Documents/Apps/rdm/node_modules/eslint/lib/cli-engine.js:371:26)
    at lint (/Users/test/Documents/Apps/rdm/node_modules/eslint-loader/index.js:26:20)
    at Object.module.exports (/Users/test/Documents/Apps/rdm/node_modules/eslint-loader/index.js:106:7)
    at WEBPACK_CORE_LOADER_EXECUTION (/Users/test/Documents/Apps/rdm/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/Users/test/Documents/Apps/rdm/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)

**Comment by nitaliano** [comment]
I haven't touched this project in over a year wouldn't be surprised if it is broken ☹️ is there something specific you were hoping to see from this project?

**Comment by karna41317** [comment]
its the problem with escope package with latest version 3.4.0. if you downgrade it like 

`npm install --save-dev escope@3.3.0` it should work

**Comment by mario-zancanaro** [comment]
Hi @unboundfire ! Thanks for your answer. It was just to give you a feedback about the installation. I'll try again soon.
